### ISSUE TITLE
45410912 - Portal 2

### ISSUE THREAD

**Issue by baka0taku2022** [xenia-canary/game-compatibility#141]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-US/Product/Portal-2/66acd000-77fe-1000-9115-d80245410912

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/1319ff6ead3c7d43af63b87be8c3ba486c8e53b5/

### Issues

Menus do not appear. Game is playable otherwise.

### Log

[xenia-log.zip](https://github.com/xenia-canary/game-compatibility/files/11367915/xenia-log.zip)

### Screenshots

![No menu](https://user-images.githubusercontent.com/106114965/235527483-0132df9e-6e32-4427-aa86-aa6148a9e250.png)

### Labels
state-gameplay gpu-drawing-corrupt gpu-drawing-missing tech-engine-source

**Comment by baka0taku2022** [comment]
Nvm. I was able to fix game by setting d3d12_readback_resolve = true.

**Comment by AmericanSlacker** [comment]
Menus do not show text as seen here.
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c522d284-f621-488d-aa5d-0d29f5c940c5" />
However, the game is somewhat playable with VERY noticeable graphical issues. Nothing that can't be temporarily fixed with F5 every now and again though. There is some moments where audio clips can hang causing it to get stuck and play continuously until a loading screen. Unless I can get to the end of the game the gameplay tag is still appropriate here.

**Comment by A1eNaz** [comment]
use `readback_resolve` for the invisible text

**Comment by BorealisEcho** [comment]
As of fbd620c_canary_experimental (2026-05-30) release, this game benefits from ZPD occlusion queries.

Set `occlusion_query = "fast"` or `occlusion_query = "strict"` to fix lighting and unoccluded lens flares.

~~Game also needs `occlusion_query_saturation=0.7` for lighting accuracy.~~

**Comment by BorealisEcho** [comment]
aee0871_canary_experimental

Finished the game with only small issues.

- Settings: `readback_resolve = "full"`, `gamma_render_target_as_unorm16 = false`
- Specs: 9800X3D / 5070Ti

### Sound:
- No issues.

### Visual:
- Game needs `gamma_render_target_as_unorm16 = false` to correct gamma, but this setting causes GLaDOS's particle effects to become corrupted, so not completely fixed.
- Occasionally a few textures wouldn't load and would default to black, rebooting xenia fixed it. Only needed to do this twice.
- Game needs `readback_resolve = "full"` to fix missing text.
- Can be upscaled without issues.

### Gameplay:
- No issues, seems stable.
- FPS is locked to 30.


### Screenshots

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/57da5354-6c75-4199-91f9-3ce8d4fb533e" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/a121e8e8-fca2-4b89-b4b9-47246d2b2664" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/d6b6dbcb-4a08-4ff1-914f-c15aff0518c2" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/91053081-9041-46b3-bc4c-86e012d874b2" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/f72bee4d-b10f-4091-898f-addc8cc44509" />

### Gamma settings comparison

- `gamma_render_target_as_unorm16 = true`

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/de311a56-eaee-4c27-bbd6-b14cdc804179" />

- `gamma_render_target_as_unorm16 = false`

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/4b0e57a2-138e-430d-913b-332c6eaf8bf3" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/9b704761-8832-4e63-a7b7-f90532203fe4" />
