### ISSUE TITLE
545408B2 - WWE 2k14

### ISSUE THREAD

**Issue by SteveChomu** [xenia-canary/game-compatibility#32]
[Marketplace](https://marketplace.xbox.com/en-us/Product/WWE-2K14/66acd000-77fe-1000-9115-d802545408b2)

Tested on https://github.com/xenia-canary/xenia-canary/commit/5cb86f7173bef8af18c6f1f99e337a1f804a77f7

# Issues:
Game gets crashing while starting Kick-off match
In 30 years of Wrestlemania mode in first match while entrance screen gets black but sound is working and then again getting same error
Frame drops and Sound flickering is happening
Game is working fine in Streak Mode and i am able to play the matches in streak mode with 30 to 45 FPS

# Log:
[xenia.zip](https://github.com/xenia-canary/game-compatibility/files/4279462/xenia.zip)

# Screenshot(s):
![75667576-e9c76080-5c9d-11ea-888b-5a704cb3e676](https://user-images.githubusercontent.com/61686894/75746677-0799d180-5d41-11ea-85cf-12a1d41baa4d.png)

# Labels:
(state-gameplay)

**Comment by BiwwytheBoi** [comment]
should this also have a crash label?

**Comment by Giuliano933** [comment]
Now. Is works this game with Xenia / Canary?

**Comment by LandFunco** [comment]
Tested on xenia-canary/xenia-canary@dc29307

Using the following special configs:
gpu = "vulkan" to prevent crashes when using D3D12
ignore_offset_for_ranged_allocations = true to prevent crashes at the start of matches

Some wrestlers will be invisible during their entrance and during their victory sequence. It does not affect every wrestler, I've not been able to figure out what it is about certain wrestlers that makes them invisible while others display fine. In the below screenshot you can see the shadow of where the wrestler's feet should be.

![Invisible](https://github.com/xenia-canary/game-compatibility/assets/76762548/53da4577-7978-4499-99fb-674e0a1104b2)

**Comment by BigRulen** [comment]
> Tested on [xenia-canary/xenia-canary@dc29307](https://github.com/xenia-canary/xenia-canary/commit/dc29307)
> 
> Using the following special configs: gpu = "vulkan" gpu_allow_invalid_fetch_constants = true ignore_offset_for_ranged_allocations: true
> 
> Some wrestlers will be invisible during their entrance and during their victory sequence. It does not affect every wrestler, I've not been able to figure out what it is about certain wrestlers that makes them invisible while others display fine. In the below screenshot you can see the shadow of where the wrestler's feet should be.
> 
> ![Invisible](https://user-images.githubusercontent.com/76762548/260336541-53da4577-7978-4499-99fb-674e0a1104b2.png)

ty so much bro game works perfectly. I really appreciated, much love.

**Comment by AlmogAmiga** [comment]
> Tested on [xenia-canary/xenia-canary@dc29307](https://github.com/xenia-canary/xenia-canary/commit/dc29307)
> 
> Using the following special configs: gpu = "vulkan" gpu_allow_invalid_fetch_constants = true ignore_offset_for_ranged_allocations: true
> 
> Some wrestlers will be invisible during their entrance and during their victory sequence. It does not affect every wrestler, I've not been able to figure out what it is about certain wrestlers that makes them invisible while others display fine. In the below screenshot you can see the shadow of where the wrestler's feet should be.
> 
> ![Invisible](https://private-user-images.githubusercontent.com/76762548/260336541-53da4577-7978-4499-99fb-674e0a1104b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NTM1MTksIm5iZiI6MTcxMDQ1MzIxOSwicGF0aCI6Ii83Njc2MjU0OC8yNjAzMzY1NDEtNTNkYTQ1NzctNzk3OC00NDk5LTk5ZmItNjc0ZTBhMTEwNGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDIxNTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OTg5Y2JkNWI2YTNiOWU5ZTJlOWZkYzhmYjY4ZmI2YTM4ZDdjNzVlYzgwZjg1OTMxMDlmMjI2OTk2OWZmMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YPSpFTq4YrEQkGqyWi1dLZp0qWllPPkFcaaQCF7zAGk)

In my case, the game was working in some sort of slow-motion and I fixed it by doing what you have done plus setting `framerate_limit = 0`.

**Comment by taitai2fly** [comment]
Does anyone know how I can get my character models to not look like this?

![Image](https://github.com/user-attachments/assets/6bed0519-5351-43ba-8aec-6df53ad6dba0)

**Comment by GlebikMoicano** [comment]
> Tested on [xenia-canary/xenia-canary@dc29307](https://github.com/xenia-canary/xenia-canary/commit/dc29307)
> 
> Using the following special configs: gpu = "vulkan" gpu_allow_invalid_fetch_constants = true ignore_offset_for_ranged_allocations: true
> 
> Some wrestlers will be invisible during their entrance and during their victory sequence. It does not affect every wrestler, I've not been able to figure out what it is about certain wrestlers that makes them invisible while others display fine. In the below screenshot you can see the shadow of where the wrestler's feet should be.
> 
> ![Invisible](https://github.com/xenia-canary/game-compatibility/assets/76762548/53da4577-7978-4499-99fb-674e0a1104b2)

Tried this, and game works perfectly, thanks

**Comment by LandFunco** [comment]
While I am glad that the settings from my post are helping people enjoy this game I also ask that you PLEASE STOP saying that the game is “working perfectly”. The seemingly random invisible wrestlers bug still exists, which takes a lot of fun out of creating wrestlers and setting up championships.

**Comment by quocbao2002** [comment]
Tested on [xenia-canary/xenia-canary@f9d4dbc](https://github.com/xenia-canary/xenia-canary/commit/f9d4dbc)

The game work fine for me. I have tried kick off, 30 years of WM and the streaks mode and i didn't notice any problem at all. 

config: 
gpu = "d3d12" 
gpu_allow_invalid_fetch_constants = true 
ignore_offset_for_ranged_allocations = true (this option need to set as "true" to prevent crash when start match)
readback_resolve = fast (need to set as "fast" or "full" to fix manager model texture error
Also this game run too fast when v sync is turn off and framelimit is off. Set v sync to "on" or set framelimit to 60 will make game run at playable speed

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/ac85e2be-f4a5-4077-9cf8-b2d1fa501e6a" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/2073509c-9fe5-431d-b28c-7c7da234a97f" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/5f383a5f-ac0f-482b-b2b6-fa33d960a50c" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/e678daa4-52f2-4e55-a9b0-c751625bd671" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/1f10e4d8-22f3-4372-8293-db056cd24673" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/d853e765-f385-4155-b847-1bc8dfab5b80" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/20bd5e58-706e-42d2-a3b3-582041ca6594" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/15682cbe-e434-41c8-aa14-6daac151e28d" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/465ff55c-e7fb-4802-9c4d-a99a2b9e2b4f" />
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/12cf9b32-7321-4029-bffd-9fc8ec1399c5" />

**Comment by harryedwardkent-sketch** [comment]
> Tested on [xenia-canary/xenia-canary@f9d4dbc](https://github.com/xenia-canary/xenia-canary/commit/f9d4dbc)
> 
> The game work fine for me. I have tried kick off, 30 years of WM and the streaks mode and i didn't notice any problem at all.
> 
> config: gpu = "d3d12" gpu_allow_invalid_fetch_constants = true ignore_offset_for_ranged_allocations = true (this option need to set as "true" to prevent crash when start match) readback_resolve = fast (need to set as "fast" or "full" to fix manager model texture error Also this game run too fast when v sync is turn off and framelimit is off. Set v sync to "on" or set framelimit to 60 will make game run at playable speed
> 
> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127228-ac85e2be-f4a5-4077-9cf8-b2d1fa501e6a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjgtYWM4NWUyYmUtZjRhNS00MDc3LTljZjgtYjJkMWZhNTAxZTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNDdkNzJiMWVmNmViOWI3NDA0MDI2ZGQ2ZWU1NjM5OGQyZDQwNTYyYWMwM2NhMTM2YmY0NGRkNGUzNjdiYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yVPXvtnLZGdA_rkOrmB-OZGw0zLoxVFiq_fBb_s3FAI"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127232-2073509c-9fe5-431d-b28c-7c7da234a97f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzItMjA3MzUwOWMtOWZlNS00MzFkLWIyOGMtN2M3ZGEyMzRhOTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMzczZjY5MmRlOWM4MTg4ODhlMzcxOTE0M2FiYzEwZjFjNjA1NzBjYzc5MWViMWExOWRlZTVkNDQ0OWJmMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9Q96L3SqC_eFwxu_ArLlJW-BB94I_TZWcviDmLe-nMI"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127230-5f383a5f-ac0f-482b-b2b6-fa33d960a50c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzAtNWYzODNhNWYtYWMwZi00ODJiLWIyYjYtZmEzM2Q5NjBhNTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMjExMDE5Y2FlNzFjNGNmNjZlODJhMjY0MThjNTU2MDI4ZGM4MmY2NWM1NTNlMTY1ZTdiMDg0YjIwMzJkNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hn8ouzePKLVuAJqWqYBuVjG-8XKIX0q-1w0Hk0BL5cA"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127229-e678daa4-52f2-4e55-a9b0-c751625bd671.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjktZTY3OGRhYTQtNTJmMi00ZTU1LWE5YjAtYzc1MTYyNWJkNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOWUxNDExNTc4MGM3OTI0YzI0YmYwMjljYTAzMDdlYzhiYTYwMjY5OGM1Nzk3N2YyMWUzNzUzNWNkMTczNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DzKe8v6oncAmP9X-DWjJbYTvRn3llHFLMNKuktEn-e8"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127235-1f10e4d8-22f3-4372-8293-db056cd24673.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzUtMWYxMGU0ZDgtMjJmMy00MzcyLTgyOTMtZGIwNTZjZDI0NjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiODAwMjJlYWM0MGFjMDdiMWFiNWMzNDA2ZmE1MGU1ZWIxNjhmMDkzN2EzOGZkMzIxYWI4MmY5NjU4NmU4MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fo44lT5deEcIWCq2gyukgMmz741qdhbPl5g50fMRisk"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127227-d853e765-f385-4155-b847-1bc8dfab5b80.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjctZDg1M2U3NjUtZjM4NS00MTU1LWI4NDctMWJjOGRmYWI1YjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxODA4ODAyM2FiMDBkOGI2Mjg0MmZiNzY0MTE5YmI3NTgxNmQ2Mzc1YTI0MWVlOThkN2YwZTgwOWU3MDQ3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6MN5AfUX-u5hgmeM2McpLTwf8VbnhOmtGz2FsDtB0nM"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127236-20bd5e58-706e-42d2-a3b3-582041ca6594.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzYtMjBiZDVlNTgtNzA2ZS00MmQyLWEzYjMtNTgyMDQxY2E2NTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YzM0YWNkNWU3ZmY5ZDkyMzdmYTQ2ZDFlZGI1OTg5ZWE5NDk4ODliYjQwZWZkMmUwZTFkMGRmM2E2Yjk2NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z-dh_A3fKes_UMiIjWv1_emuWx1Ndph9BQgQlZnvHMA"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127233-15682cbe-e434-41c8-aa14-6daac151e28d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzMtMTU2ODJjYmUtZTQzNC00MWM4LWFhMTQtNmRhYWMxNTFlMjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNTcxNmZhYTU3OTY4NmI5NTA5ODM0MTcyZjJlNzQwNmFlZjFiNDgwNzE4Y2E3ZDczNjg4N2QwYTk4MjhlYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gr9hauhRAgwIS1gk1iq7uLN5A0ACNnUxdkze4veBvgg"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127231-465ff55c-e7fb-4802-9c4d-a99a2b9e2b4f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzEtNDY1ZmY1NWMtZTdmYi00ODAyLTljNGQtYTk5YTJiOWUyYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNWY0YTJmOGY3ZTc3NzkzYzA0Yjk1NzUyMmQzZjgxNGNkODBjNGM5ZmMxNzAyY2RkNjdlMTFkYWFiOTllNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eTrxVUaRRLnDuoeGS3Q33CkM94wOGd00Nz5Yh5fzyXY"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127234-12cf9b32-7321-4029-bffd-9fc8ec1399c5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzQtMTJjZjliMzItNzMyMS00MDI5LWJmZmQtOWZjOGVjMTM5OWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyODY0ZTM0MTJkOGRjNDg4MGNmNmQzNDRjMGFjMGE2NDkxNWU5Y2I3YWJmMWZhMTgyNjc5MWQ1YTcyNjlkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2iRw_UCxg2-buFoHwOHoRFuvEwRP-suE2iCieg69h0M">

Can you explain to a noob the "fast" bit. I cant put that into the text file can i ?

**Comment by quocbao2002** [comment]
> > Tested on [xenia-canary/xenia-canary@f9d4dbc](https://github.com/xenia-canary/xenia-canary/commit/f9d4dbc)
> > The game work fine for me. I have tried kick off, 30 years of WM and the streaks mode and i didn't notice any problem at all.
> > config: gpu = "d3d12" gpu_allow_invalid_fetch_constants = true ignore_offset_for_ranged_allocations = true (this option need to set as "true" to prevent crash when start match) readback_resolve = fast (need to set as "fast" or "full" to fix manager model texture error Also this game run too fast when v sync is turn off and framelimit is off. Set v sync to "on" or set framelimit to 60 will make game run at playable speed
> > <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127228-ac85e2be-f4a5-4077-9cf8-b2d1fa501e6a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjgtYWM4NWUyYmUtZjRhNS00MDc3LTljZjgtYjJkMWZhNTAxZTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNDdkNzJiMWVmNmViOWI3NDA0MDI2ZGQ2ZWU1NjM5OGQyZDQwNTYyYWMwM2NhMTM2YmY0NGRkNGUzNjdiYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yVPXvtnLZGdA_rkOrmB-OZGw0zLoxVFiq_fBb_s3FAI"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127232-2073509c-9fe5-431d-b28c-7c7da234a97f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzItMjA3MzUwOWMtOWZlNS00MzFkLWIyOGMtN2M3ZGEyMzRhOTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMzczZjY5MmRlOWM4MTg4ODhlMzcxOTE0M2FiYzEwZjFjNjA1NzBjYzc5MWViMWExOWRlZTVkNDQ0OWJmMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9Q96L3SqC_eFwxu_ArLlJW-BB94I_TZWcviDmLe-nMI"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127230-5f383a5f-ac0f-482b-b2b6-fa33d960a50c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzAtNWYzODNhNWYtYWMwZi00ODJiLWIyYjYtZmEzM2Q5NjBhNTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMjExMDE5Y2FlNzFjNGNmNjZlODJhMjY0MThjNTU2MDI4ZGM4MmY2NWM1NTNlMTY1ZTdiMDg0YjIwMzJkNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hn8ouzePKLVuAJqWqYBuVjG-8XKIX0q-1w0Hk0BL5cA"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127229-e678daa4-52f2-4e55-a9b0-c751625bd671.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjktZTY3OGRhYTQtNTJmMi00ZTU1LWE5YjAtYzc1MTYyNWJkNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOWUxNDExNTc4MGM3OTI0YzI0YmYwMjljYTAzMDdlYzhiYTYwMjY5OGM1Nzk3N2YyMWUzNzUzNWNkMTczNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DzKe8v6oncAmP9X-DWjJbYTvRn3llHFLMNKuktEn-e8"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127235-1f10e4d8-22f3-4372-8293-db056cd24673.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzUtMWYxMGU0ZDgtMjJmMy00MzcyLTgyOTMtZGIwNTZjZDI0NjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiODAwMjJlYWM0MGFjMDdiMWFiNWMzNDA2ZmE1MGU1ZWIxNjhmMDkzN2EzOGZkMzIxYWI4MmY5NjU4NmU4MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fo44lT5deEcIWCq2gyukgMmz741qdhbPl5g50fMRisk"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127227-d853e765-f385-4155-b847-1bc8dfab5b80.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjctZDg1M2U3NjUtZjM4NS00MTU1LWI4NDctMWJjOGRmYWI1YjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxODA4ODAyM2FiMDBkOGI2Mjg0MmZiNzY0MTE5YmI3NTgxNmQ2Mzc1YTI0MWVlOThkN2YwZTgwOWU3MDQ3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6MN5AfUX-u5hgmeM2McpLTwf8VbnhOmtGz2FsDtB0nM"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127236-20bd5e58-706e-42d2-a3b3-582041ca6594.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzYtMjBiZDVlNTgtNzA2ZS00MmQyLWEzYjMtNTgyMDQxY2E2NTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YzM0YWNkNWU3ZmY5ZDkyMzdmYTQ2ZDFlZGI1OTg5ZWE5NDk4ODliYjQwZWZkMmUwZTFkMGRmM2E2Yjk2NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z-dh_A3fKes_UMiIjWv1_emuWx1Ndph9BQgQlZnvHMA"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127233-15682cbe-e434-41c8-aa14-6daac151e28d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzMtMTU2ODJjYmUtZTQzNC00MWM4LWFhMTQtNmRhYWMxNTFlMjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNTcxNmZhYTU3OTY4NmI5NTA5ODM0MTcyZjJlNzQwNmFlZjFiNDgwNzE4Y2E3ZDczNjg4N2QwYTk4MjhlYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gr9hauhRAgwIS1gk1iq7uLN5A0ACNnUxdkze4veBvgg"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127231-465ff55c-e7fb-4802-9c4d-a99a2b9e2b4f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzEtNDY1ZmY1NWMtZTdmYi00ODAyLTljNGQtYTk5YTJiOWUyYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNWY0YTJmOGY3ZTc3NzkzYzA0Yjk1NzUyMmQzZjgxNGNkODBjNGM5ZmMxNzAyY2RkNjdlMTFkYWFiOTllNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eTrxVUaRRLnDuoeGS3Q33CkM94wOGd00Nz5Yh5fzyXY"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127234-12cf9b32-7321-4029-bffd-9fc8ec1399c5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE5NDg2NDksIm5iZiI6MTc3MTk0ODM0OSwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzQtMTJjZjliMzItNzMyMS00MDI5LWJmZmQtOWZjOGVjMTM5OWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI0VDE1NTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyODY0ZTM0MTJkOGRjNDg4MGNmNmQzNDRjMGFjMGE2NDkxNWU5Y2I3YWJmMWZhMTgyNjc5MWQ1YTcyNjlkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2iRw_UCxg2-buFoHwOHoRFuvEwRP-suE2iCieg69h0M">
> 
> Can you explain to a noob the "fast" bit. I cant put that into the text file can i ?

sorry for reply late, in xenia_canary latest version readback_resolve have three option to choose,none, fast or full. You should choose fast or full because if you choose none, some wrestler or manager like bobby the brain hennan wrestlemania 1 outfit will have weird black texture like you see in my image. Choose fast or full will fix it but it make game run slower in match if you have weak computer or laptop

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/cb007295-c250-4afb-afd0-393cf15ea5f4" />

Here if you set readback_resolve to fast or full

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/4917f72b-7fcd-4239-87ef-656d6aa38b6a" />

**Comment by anuj120103-cpu** [comment]
<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/17d4732c-4647-46d5-94ad-9ff133c3f749" />
My game crashes when playing edge vs mick foley match at 30 yrs of Wrestlemania mode

[xenia.log](https://github.com/user-attachments/files/26161104/xenia.log)

**Comment by dman42439-lgtm** [comment]
how do i find the ignore_offset_for_ranged_allocations in the config i cant find it anywhere i find the other ones just not that one can someone send a screenshot where it is? and how do i fix my game just pausing when the wrestlers are in the ring and the match is about to start

**Comment by dman42439-lgtm** [comment]
> Tested on [xenia-canary/xenia-canary@f9d4dbc](https://github.com/xenia-canary/xenia-canary/commit/f9d4dbc)
> 
> The game work fine for me. I have tried kick off, 30 years of WM and the streaks mode and i didn't notice any problem at all.
> 
> config: gpu = "d3d12" gpu_allow_invalid_fetch_constants = true ignore_offset_for_ranged_allocations = true (this option need to set as "true" to prevent crash when start match) readback_resolve = fast (need to set as "fast" or "full" to fix manager model texture error Also this game run too fast when v sync is turn off and framelimit is off. Set v sync to "on" or set framelimit to 60 will make game run at playable speed
> 
> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127228-ac85e2be-f4a5-4077-9cf8-b2d1fa501e6a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjgtYWM4NWUyYmUtZjRhNS00MDc3LTljZjgtYjJkMWZhNTAxZTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkM2I0OTcxZTNjMWJiOTMxY2I5ZDI1Y2E2YTNiMTBiOWQ3OGFlNjJlZjM2NmViZGE1OTUyYjE1ZTg2NGVmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.IxGP-utBWHfn2AWhK1gaAIo478oWUydpR2x1WPQ1oRw"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127232-2073509c-9fe5-431d-b28c-7c7da234a97f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzItMjA3MzUwOWMtOWZlNS00MzFkLWIyOGMtN2M3ZGEyMzRhOTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNWFlZjEwMzIzMDZmMzZlZTg5MWY4N2E3ZjFkNzA0NDM5ZGY5NmY5MjljYTFkY2E1YmM3OWZmMGQ4NjU0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.GeEI5HoKhXRgnlpNzZUNnGYIE_EYd4DhBxmAWbIKFcY"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127230-5f383a5f-ac0f-482b-b2b6-fa33d960a50c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzAtNWYzODNhNWYtYWMwZi00ODJiLWIyYjYtZmEzM2Q5NjBhNTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MmVkNDA5YmUyNjc0ZWI4NjliNzU5Yzg4OGMxMjZiMDM4YzFkOGIwZDZmOGQxNjE4ZDA2MzQ0NDA2YjdlNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.HLWJ9jAVFcnS11E7U3JguLRW8dOSypt-EJwJ61oCt8s"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127229-e678daa4-52f2-4e55-a9b0-c751625bd671.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjktZTY3OGRhYTQtNTJmMi00ZTU1LWE5YjAtYzc1MTYyNWJkNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzODU1N2UzZWIyNDg2ODVjMjk1ZTMzYWNlOWVlNDA2MGNlNjRhNzIyNGZmY2EwNWU4ZDcxNzJjZjc3NGQxMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.gfifLYcA2Y8Sjv9uh-rJx9gdtKKJc_tji6lf75I8wjs"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127235-1f10e4d8-22f3-4372-8293-db056cd24673.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzUtMWYxMGU0ZDgtMjJmMy00MzcyLTgyOTMtZGIwNTZjZDI0NjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZjA1ZTMzODNiYjJmMmRkMGQyOTI2ZDQxZDViNzZlOTQ0YTI5ZTRiYTJmNWFlY2U0MzY2NzA4NzExNjU0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.W4jG0N1svkMj1fJB4xnuBc-jWq8UA2_QAUHXTWSqTTM"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127227-d853e765-f385-4155-b847-1bc8dfab5b80.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMjctZDg1M2U3NjUtZjM4NS00MTU1LWI4NDctMWJjOGRmYWI1YjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzYzNGNlZGY3ZGUxODRmMWUwNTVhYTg2ODZmZDFkZjNkNWJkYmViMDFkMzhlNjc2NDYwNWU5NjBjZWU1ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.V_qJ1XBx33OElGvin0pT0Q6pZAWzPyIC6vUuxjr7_ak"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127236-20bd5e58-706e-42d2-a3b3-582041ca6594.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzYtMjBiZDVlNTgtNzA2ZS00MmQyLWEzYjMtNTgyMDQxY2E2NTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOTQxNWJlNzIyNGExMGQ2NDE1YWY4ZDgwZmEwZWJmMmNhNWI1NTRkMmIzNzY5ZDcyNjkzOTE2MGE5M2M4NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.GY56AShSly3aVXfFUJwvXLtadmJ7atP8WaK4E_cxpnE"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127233-15682cbe-e434-41c8-aa14-6daac151e28d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzMtMTU2ODJjYmUtZTQzNC00MWM4LWFhMTQtNmRhYWMxNTFlMjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YmJhNmUzOTdkNzY2OTYxZjVkNmI3YWYzZWVjMmMxM2I2YzdiMWFjZjhjNTEwZTk2MDRkYWQwNTA4MTgxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.UuM_iK8tbWRsewvl7QPry0DJJG5RxLgVCDIdmXTY-1c"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127231-465ff55c-e7fb-4802-9c4d-a99a2b9e2b4f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzEtNDY1ZmY1NWMtZTdmYi00ODAyLTljNGQtYTk5YTJiOWUyYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NDVkODdlZGU1MWM4MjhhNGRiNTViNjBiZTQwZjRiZTcxZWJkMWQwNDI5ZDExMzdjOWNiYWRjMDMyY2ViZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.-AVMAgyODKy3_keg3ZORUrjoZXXN7gYSkZ7Nl2WQPmI"> <img alt="Image" width="1280" height="720" src="https://private-user-images.githubusercontent.com/79297878/550127234-12cf9b32-7321-4029-bffd-9fc8ec1399c5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcyNTk4MjgsIm5iZiI6MTc3NzI1OTUyOCwicGF0aCI6Ii83OTI5Nzg3OC81NTAxMjcyMzQtMTJjZjliMzItNzMyMS00MDI5LWJmZmQtOWZjOGVjMTM5OWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI3VDAzMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZDAyYTAyMDNlN2VkMTQwMmRlZTc2ZGFkYTgyNjA5N2U0OTc3NjU5NTVlMTg3YWIzMjdiZTk4Yjc1ZjBlOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.BMXqcVxtHISNU2nFAnxxTSbZkSbYl1lvF8NK0upVVHQ">

how do i find the ignore_offset_for_ranged_allocations in the config i cant find it anywhere i find the other ones just not that one can someone send a screenshot where it is? and how do i fix my game just pausing when the wrestlers are in the ring and the match is about to start

**Comment by officialgeek** [comment]
<img width="962" height="578" alt="Image" src="https://github.com/user-attachments/assets/4394a528-1704-4a81-89f7-bef92aadf698" />

Game crashed at entrences on 2799234_canary_experimental

[xenia.log](https://github.com/user-attachments/files/30051597/xenia.log)
