### ISSUE TITLE
4D53084D - Forza Motorsport 3

### ISSUE THREAD

**Issue by nfxw** [xenia-canary/game-compatibility#409]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Wiki page (optional)

https://github.com/xenia-canary/game-compatibility/wiki/...

### Xenia Canary version

https://github.com/xenia-canary/xenia-canary/commit/09be7e874a9f4eaec23d779923b143d8d1006aa6

### Issues

1440p - texture flickering.
Issue with tracks may be fixed by changing files of the game, square shadows can't be fixed, only can be disabled. 

### Log

[xenia.log](https://github.com/user-attachments/files/18389186/xenia.log)

### Screenshots

![1](https://github.com/user-attachments/assets/64b47551-f942-46a5-bdd7-e9826bc5381e)

### Labels

state-gameplay

**Comment by Mgcad37** [comment]
The issue with the tracks can be fixed by setting readback_resolve to fast and it may drop a bit of fps

**Comment by ReSkipp** [comment]
### Xenia Canary version

https://github.com/xenia-canary/xenia-canary/commit/9132035a515d4fe075178b857065d6514768bf75

### Log

[xenia.log](https://github.com/user-attachments/files/23322808/xenia.log)

Taken from a freeplay race.

<br>

Using an RX 5700, with a Ryzen 5 3600.

<br>

I was able to get the game acting a little better using readback_resolve, though that didn't fix all of the issues with the road, just slightly helped it.

Fixed the audio skipping music tracks every 5 seconds while racing by setting use_dedicated_xma_thread to false, though this should be tested a bit more.

Player car shadows while racing sometimes fix themselves for a brief moment, but usually are a black rectangle. There is also artifacting of the shadow texture right below the car while racing and while picking new rims or other parts in the shop; it's the one that doesn't change with the sun's direction.

Road corruption gets worse the faster you go, and there are also artifacts that appear for a frame or two on the road. While paused though, the road corruption goes away. The bumper camera mirror also has garbage displayed sometimes, and overall looks squished.

There is also a problem with car reflections mid race, where the texture for reflection used has incorrect draws.

None of these artifacts are fixed with F5.

Another thing I just noticed was the doppler effect when cars go by seems to be broken and jumbled, but I'm not sure if I should add a tag for that minor of an issue.

<details>
<summary>Images and Car Reflection details</summary>

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e9c3c716-0687-4552-a7d2-6c7c484477ec" />

<img width="1920" height="1079" alt="Image" src="https://github.com/user-attachments/assets/95b6b2b0-1b36-4fb4-9776-71fae1b7f390" />

<img width="1920" height="1077" alt="Image" src="https://github.com/user-attachments/assets/10447996-9f2e-4c15-862c-2ab8323ef2f3" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/51553ebb-2453-41d2-b78a-237b899ca9c1" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2d8aa550-9914-4142-9136-b495a0efd473" />

<details>
<summary>Car Reflection Explanation</summary>
In RenderDoc, I took a few captures, and noticed that there was some corruption in some draws for the reflection texture for the car.

<img width="925" height="631" alt="Image" src="https://github.com/user-attachments/assets/0d349b95-efa8-4fa6-96b3-689aa1502109" />

A few more draws added onto the corruption.

<img width="1033" height="675" alt="Image" src="https://github.com/user-attachments/assets/4886c9ad-31ab-4846-ac09-d6250668fc17" />

<img width="617" height="622" alt="Image" src="https://github.com/user-attachments/assets/69297a46-459d-43a1-8453-261350ca4fef" />

Unsure if this texture is one of the final reflection images, but I wouldn't be surprised since it looks quite similar to the other texture that I did spot being applied.

<img width="700" height="701" alt="Image" src="https://github.com/user-attachments/assets/742b911e-3c3c-4fd2-9f17-255695582956" /> 

This is the texture that I did spot being used, since you can see the red "Virgin" sign in the reflection of the car.

<img width="564" height="542" alt="Image" src="https://github.com/user-attachments/assets/eaee0225-49b9-4cee-a064-e4cf2560b3fd" />

<img width="1044" height="671" alt="Image" src="https://github.com/user-attachments/assets/f12b38ac-d21a-41fb-8e4b-550e10b12acc" />

</details>

Sorry for the image spam by the way, I took a lot of images and tried to show the best ones here.

</details>

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/433d5658-e292-4e3a-8c09-4a746e1c9914" />

<br>

### Labels

state-gameplay

gpu-drawing-corrupt

gpu-readback

**Comment by ReSkipp** [comment]
> ### Xenia Canary version
> 
> [xenia-canary/xenia-canary@9132035](https://github.com/xenia-canary/xenia-canary/commit/9132035a515d4fe075178b857065d6514768bf75)
> ### Log
> 
> [xenia.log](https://github.com/user-attachments/files/23322808/xenia.log)
> 
> Taken from a freeplay race.
> 
> Using an RX 5700, with a Ryzen 5 3600.
> 
> I was able to get the game acting a little better using readback_resolve, though that didn't fix all of the issues with the road, just slightly helped it.
> 
> Fixed the audio skipping music tracks every 5 seconds while racing by setting use_dedicated_xma_thread to false, though this should be tested a bit more.
> 
> Player car shadows while racing sometimes fix themselves for a brief moment, but usually are a black rectangle. There is also artifacting of the shadow texture right below the car while racing and while picking new rims or other parts in the shop; it's the one that doesn't change with the sun's direction.
> 
> Road corruption gets worse the faster you go, and there are also artifacts that appear for a frame or two on the road. While paused though, the road corruption goes away. The bumper camera mirror also has garbage displayed sometimes, and overall looks squished.
> 
> There is also a problem with car reflections mid race, where the texture for reflection used has incorrect draws.
> 
> None of these artifacts are fixed with F5.
> Images and Car Reflection details
> 
> <img alt="Image" width="1920" height="1080" src="https://private-user-images.githubusercontent.com/89713049/509293071-433d5658-e292-4e3a-8c09-4a746e1c9914.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIyNTUzNzUsIm5iZiI6MTc2MjI1NTA3NSwicGF0aCI6Ii84OTcxMzA0OS81MDkyOTMwNzEtNDMzZDU2NTgtZTI5Mi00ZTNhLThjMDktNGE3NDZlMWM5OTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTA0VDExMTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MGI4NjM2OTBmNzQzYmI1OWE5YWI4ZTYwMDdmMzdmNjc1ZDcwNjUzNDNiYmU5Y2VkMTM1NTQ4YmQxMGJlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nIoCoDwEYMLwteRk14_SGbUA0xhEpw6g3vmucID0NhI">
> ### Labels
> 
> state-gameplay
> 
> gpu-drawing-corrupt
> 
> gpu-readback

Another thing I just noticed was the doppler effect when cars go by seems to be broken and jumbled, but I'm not sure if I should add a tag for that minor of an issue.

**Comment by nfxw** [comment]
Setting readback_resolve to fast on latest canary fixed the issue with road texture, but still have issue with square shadows.
Performance is also great, 60fps solid.
Also setting use_dedicated_xma_thread to false fix skipping radio music.

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/0087641f-600e-4b92-b522-e72a81fdf563" />

**Comment by nfxw** [comment]
For those who wants to install dlc (you need to get Disc 2 of the game).
Download extract-xiso program, drop iso disc into xiso program, then you'll have folder.
In xenia canary emulator: File - Install content, then navigate to Content\0000000000000000\4D53084D\00000002, select all, then click to open, after that wait until dlc will be isntalled, that's it, dlc is now installed.
Works for fm2 and fm4 too.

**Comment by nfxw** [comment]
With latest xenia edge release you can now combine readback_resolve with resolution scaling.
Almost zero flickering, but square shadow still presents, but not in 1st person view.

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/b9103ec4-ec29-45b8-8b80-6eece58a6978" />
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/891fa818-9fa3-4a3f-8579-babd2e3b864e" />

**Comment by BorealisEcho** [comment]
As of fbd620c_canary_experimental (2026-05-30) release, this game benefits from ZPD occlusion queries.

Set `occlusion_query = "fast"` or `occlusion_query = "strict"` to fix unoccluded lens flares.

**Comment by nfxw** [comment]
Square shadows are fixed on edge 2432190 and canary d119505.

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/362f4767-88fa-437e-b3d7-27aa01dcad11" />

**Comment by nfxw** [comment]
The game is fully playble.
All of the issues that mentioned above are fixed.

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/73a6f300-7a2c-45d4-8572-3efd9b75acb8" />
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/8fdd15b3-d1f2-45a9-945b-cb7713382292" />

**Comment by BorealisEcho** [comment]
Should be said that the game requires `readback_resolve = "full"`

**Comment by rj909559** [comment]
> Should be said that the game requires `readback_resolve = "full"`

This does not fix the road issue on latest canary build

**Comment by goldislead** [comment]
> > Should be said that the game requires `readback_resolve = "full"`
> 
> This does not fix the road issue on latest canary build

readback_resolve = "fast" & resolve_check_number_format = true will mostly solve the road issue.
But I guess car thumbnails still require full readback.

**Comment by fencethetrader** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/ace2e49f-32f2-453b-b274-1e36f8082146" />
glitchy textures on 2x resolution (also readback resolve is set to full)

**Comment by fencethetrader** [comment]
https://drive.google.com/file/d/137KI5vXYAaFmNoy9ex1dD0YijVDakBf4/view?usp=sharing
also broken focus for some reason (it's likely a xenia-general issue)

**Comment by nfxw** [comment]
@fencethetrader 
The issue with thumbnails in forza games related to old saves.
I've got old horizon saves and with latest canary some thumbnails don't appear, but if sold car with broken thumbnail and then buy it, then you've got proper render thumbnail.
Same applied to motorsport games.

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/f26381e6-712d-4f6d-ad50-267b5fd79c87" />
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/1d4e83d6-e3ca-4a2b-8f36-16db918ae33d" />
