### ISSUE TITLE
5553084C - Child of Eden

### ISSUE THREAD

**Issue by mrtmilv** [xenia-canary/game-compatibility#495]
### Validation

- [x] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [x] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [x] This issue isn't for help (tech support) with Xenia, or a game.
- [x] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link (optional)

https://www.xbox.com/en-us/games/store/child-of-eden/bsfn4w47nct4

### Xenia Canary version

https://github.com/xenia-canary/xenia-canary/commit/fbacd3c12d745febcf31c40f587d084f57ca5cd3

### Issues

Severe graphical issues after passing the first level. Only the Matrix level is playable. The 'guppies' on the Matrix level are also stuck together and don't spread around.

### Log

[xenia.log](https://github.com/user-attachments/files/18915532/xenia.log)

### Screenshots

![Image](https://github.com/user-attachments/assets/f293bfee-ec65-46bc-afb9-6b5f7f4e9025)

### Labels

gpu-drawing-corrupt

**Comment by A1eNaz** [comment]
can the graphical issues be fixed with `clear_memory_page_state = true`?

**Comment by mrtmilv** [comment]
This solved most of the rendering issues in the beginning of the Evolution level, but the whale boss fight still has issues which make it unplayable. Also, some surrounding particles were and still are being rendered wrong (they look like cubes), I believe, but I can't compare the visuals with the Xbox version now, unfortunately. The 'guppies' are still stuck in Evolution archive, too.
The game also stutters a little whenever a new entity is about to appear on the screen or between the levels. 

[xenia.log](https://github.com/user-attachments/files/18925000/xenia.log)

![Image](https://github.com/user-attachments/assets/167db308-b0d2-46c5-8ade-80dd880071db)

![Image](https://github.com/user-attachments/assets/6e767ac8-ba6f-4e2f-a483-5d824959cbc7)

**Comment by mrtmilv** [comment]
Tested just now on 78f97f8. The rendering has gotten better on the whale fight, but still unplayable - the red targets are not visible.

[xenia.log](https://github.com/user-attachments/files/18925105/xenia.log)
The stuck 'guppies' (on the right from the blue circular cursor)
![Image](https://github.com/user-attachments/assets/ab8fcecd-d514-4358-b464-d92632d27171)
The whale. The target under the blue cursor should be red. No more full-screen rendering issues.
![Image](https://github.com/user-attachments/assets/f6f491fc-14c6-4280-aa10-45543a1939cc)
The cube particles. Watched the YouTube video of the level - they should be there, but not this much. Some particles are also missing.
![Image](https://github.com/user-attachments/assets/f1523a2b-b665-4dba-9ede-0a97e9e1aedd)

**Comment by mrtmilv** [comment]
Stutters have become less noticeable on 9555e7b, overall performance has improved a bit. However, all the same graphical issues persist.

[xenia.log](https://github.com/user-attachments/files/19003981/xenia.log)

**Comment by mrtmilv** [comment]
Tested on f833eff. Particles now look better and some graphical issues have been lifted. However, the performance is now way worse and the game stutters way more often since my previous update on the issue.

[xenia.log](https://github.com/user-attachments/files/19192163/xenia.log)
